// File: preamble.c
// Contents: Contains Preamble, used to generate correct ASM code preabmle

#include "atto-C.h"


void preamble(char *sourcefilename)
{
    fprintf(asmfile, "; Assembly program generated by Bryce Natter's compiler.\n\n");
    fprintf(asmfile, "    TITLE  %s\n", sourcefilename);
    fprintf(asmfile, "    .686P\n");
    fprintf(asmfile, "    .model  flat\n\n");
    fprintf(asmfile, "INCLUDELIB MSVCRTD\n");
    fprintf(asmfile, "INCLUDELIB OLDNAMES\n\n");
}

void postamble()
{
    fprintf(asmfile, "END\n");
    fclose(asmfile);
}
