; Assembly program generated by Bryce Natter's compiler.

    TITLE  expression-test-3.c
    .686P
    .model  flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES


PUBLIC _add_test
;    COMDAT _add_test

_TEXT    SEGMENT
_add_test    PROC          ; COMDAT

   push  ebp
   mov   ebp,esp
   sub   esp,_add_test_locals$
   push  ebx
   push  esi
   push  edi
_a$ = 8
_b$ = 12
; Line 10
    push eax
    mov  eax, DWORD PTR _a$[ebp]
    push eax
    mov  eax, DWORD PTR _b$[ebp]
    pop ebx
    add eax,ebx
    pop ebx        ; clean up stack 
